### ISSUE TITLE
TypeError when accessing `.value` on Inst 

### ISSUE THREAD

**Issue by leonardt** [phanrahan/peak#7]
```python
from peak.pe1.asm import add

inst = add()
print(inst.value)
```

results in

```
Traceback (most recent call last):
  File "/tmp/a.py", line 4, in <module>
    print(inst.value)
  File "/Users/lenny/repos/peak/peak/adt.py", line 90, in value
    return dc.astuple(self)
  File "/Users/lenny/miniconda3/lib/python3.7/dataclasses.py", line 1053, in astuple
    return _astuple_inner(obj, tuple_factory)
  File "/Users/lenny/miniconda3/lib/python3.7/dataclasses.py", line 1060, in _astuple_inner
    value = _astuple_inner(getattr(obj, f.name), tuple_factory)
  File "/Users/lenny/miniconda3/lib/python3.7/dataclasses.py", line 1069, in _astuple_inner
    return copy.deepcopy(obj)
  File "/Users/lenny/miniconda3/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "/Users/lenny/miniconda3/lib/python3.7/enum.py", line 44, in _break_on_call_reduce
    raise TypeError('%r cannot be pickled' % self)
TypeError: <ALU.Add> cannot be pickled
```

**Comment by leonardt** [comment]
This doesn't work in python 3.7.0, but it works in python 3.7.2
